Amp 54551 ampli java v2 example
amplitude/ampli-examples pull request #111
Opened 2022-06-14 00:12 UTC by yuhao900914

2022-06-14 00:12 UTC, yuhao900914 commented
Draft pr. Still need to fix the test.

2022-06-16 01:08 UTC, justin-fiedler requested changes

2022-06-16 01:14 UTC, yuhao900914 commented on android/java/v2/AmpliApp/app/src/main/java/com/amplitude/ampli/Ampli.java
> +    }
I think I misunderstood that! Will remove this.

2022-06-16 20:50 UTC, justin-fiedler approved these changes

2022-06-18 06:06 UTC, qingzhuozhen approved these changes

2022-06-22 23:48 UTC, merged