AMP-58795 React Native V2 examples
amplitude/ampli-examples pull request #133
Opened 2022-08-22 10:30 UTC by falconandy

2022-08-23 17:24 UTC, justin-fiedler requested changes
Looking good. See nits.

2022-08-23 17:24 UTC, justin-fiedler commented on react-native/javascript/v2/AmpliApp/README.md
> +    * [middleware/*](src/middleware) - Example middlewares for Segment and Event filtering
*plugins

2022-08-23 17:33 UTC, falconandy commented on react-native/javascript/v2/AmpliApp/README.md
> +    * [middleware/*](src/middleware) - Example middlewares for Segment and Event filtering
Fixed

2022-08-23 17:33 UTC, falconandy commented on react-native/typescript/v2/AmpliApp/README.md
> +    * [middleware/*](src/middleware) - Example middlewares for Segment and Event filtering
Fixed

2022-08-23 17:33 UTC, falconandy commented on react-native/javascript/v2/AmpliApp/README.md
> +    * [middleware/*](src/middleware) - Example middlewares for Segment and Event filtering
Fixed

2022-08-24 16:11 UTC, justin-fiedler approved these changes

2022-08-24 16:12 UTC, merged