AMP-64549 java changes after mutliple environments codegen changes
amplitude/ampli-examples pull request #165
Opened 2022-11-29 18:47 UTC by igrlk

Re-run `ampli pull`

2022-11-30 18:46 UTC, justin-fiedler approved these changes

2022-12-01 10:29 UTC, falconandy requested changes
![image](https://user-images.githubusercontent.com/9509929/205028609-695ef3c3-33bf-4c87-8351-ee9f87fbf334.png)
![image](https://user-images.githubusercontent.com/9509929/205028817-e9ae86fd-ac2a-4892-9418-94e6260a9705.png)
![image](https://user-images.githubusercontent.com/9509929/205029158-f96d7c63-5138-45c1-8313-2a48b9e00941.png)

2022-12-01 14:37 UTC, igrlk commented
Fixed, @falconandy

2022-12-01 14:47 UTC, falconandy approved these changes

2022-12-02 13:52 UTC, merged