AMP-64549 kotlin changes after mutliple environments codegen changes
amplitude/ampli-examples pull request #166
Opened 2022-11-29 19:09 UTC by igrlk

Re-run `ampli pull`

2022-11-30 18:46 UTC, justin-fiedler approved these changes

2022-12-01 09:51 UTC, falconandy requested changes
![image](https://user-images.githubusercontent.com/9509929/205021534-ffe1ea3d-8858-40c9-86dc-df52377f6e6d.png)
![image](https://user-images.githubusercontent.com/9509929/205021666-f8b9e1e5-c76b-406a-8509-38406158b0ad.png)

2022-12-01 15:05 UTC, igrlk commented
Thanks @falconandy - fixed

2022-12-01 15:19 UTC, falconandy approved these changes

2022-12-02 13:52 UTC, merged