AMP-46510 Java builders
amplitude/ampli-examples pull request #22
Opened 2021-12-18 07:12 UTC by falconandy

2021-12-21 04:29 UTC, justin-fiedler requested changes
@falconandy looks good but I spoke with the team and there was a heavy preference to keep the `MyEvent.builder()` method in Java. Main reason being it is a common, expected pattern in Java albeit more verbose.

Another benefits of `builder()` method:
- Single entry point for all Event classes (always SomeEvent.builder(), vs SomeEvent.someProperty())
- Keep the generated Event classes more compact for Events with only optional params
- Builders can be overridden in a single location in the case of subclassing

2021-12-21 17:52 UTC, falconandy commented
@justin-fiedler `.builder()` is restored

2021-12-22 02:14 UTC, justin-fiedler requested changes
Overall looks good, see comments.

2021-12-22 02:14 UTC, justin-fiedler commented on android/java/AmpliApp/app/src/main/java/com/amplitude/ampli/Ampli.java
> +    public void identify(String userId, Identify properties) {
Ideally in the future we will have Builders for both Properties and Events. As discussed before to support strong object properties well we will want something like below. Given Java's verbosity I like the builders you implemented on the Event classes (compared to making new Event Property classes with own builders.) In the future we can create Property classes + builders for Property Groups.

```
MyEvent.builder().requiredProp(1).propertyGroupProp(
  PropertyGroupProp.builder().foo(true).build()
).optProp("cool").build()
```

2021-12-22 12:23 UTC, falconandy commented on android/java/AmpliApp/app/src/main/java/com/amplitude/ampli/Ampli.java
> +    public void identify(String userId, Identify properties) {
Renamed to `event`.
We will need builders for nested typed properties. We can still use event builders for top level.

2021-12-23 00:16 UTC, justin-fiedler approved these changes

2021-12-23 00:16 UTC, merged