AMP-48199 Updated iOS codegen (added groupIdentify support/tests)
amplitude/ampli-examples pull request #57
Opened 2022-02-15 07:32 UTC by falconandy

2022-02-17 21:54 UTC, justin-fiedler requested changes

2022-02-18 06:01 UTC, falconandy commented on ios/objective-c/AmpliObjectiveCSampleApp/AmpliObjectiveCSampleApp/AppDelegate.m
> +    [ampli groupIdentify:@"ampli group type" groupName:@"ampli swift group" event:[Group requiredBoolean: true builderBlock:^(GroupBuilder *b) {
Fixed

2022-02-23 02:31 UTC, qingzhuozhen approved these changes

2022-02-23 17:01 UTC, justin-fiedler approved these changes

2022-02-23 17:01 UTC, merged