AMP-51865 Added branch mapping merge check to PR CI action
amplitude/ampli-examples pull request #86
Opened 2022-04-08 16:03 UTC by falconandy

2022-04-22 23:50 UTC, dnsproxyserver01 approved these changes

2022-04-24 21:57 UTC, qingzhuozhen reviewed
lgtm, just the check seems failed

2022-04-26 15:53 UTC, justin-fiedler requested changes
@falconandy please add implementation to the examples to get the ampli status checks to pass.

2022-04-27 18:10 UTC, justin-fiedler approved these changes

2022-04-27 18:11 UTC, merged